services:
  - type: web
    name: ai-recommendation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.17
      - key: BACKEND_URL
        sync: false # This will prompt you to enter the value in the Render dashboard